#
#   Copyright 2012 Glencoe Software, Inc. All rights reserved.
#   Use is subject to license terms supplied in LICENSE.txt
#

# Subdirectory build for the Training examples.
# See ../SConstruct for more information.

import os
Import('env libs ice_config get_targets')
files = ["Model"]

targets = get_targets(env, "Training", "training.Setup", "java/src")

# PREPARING SCONS EXECUTION: =================================
#
Default(targets)
